algo = input("Digite algo:")
print("O tipo do valor que você enviou é:", type(algo))
print("Somente espaços:", algo.isspace())
print("Somente MAIÚSCULAS:", algo.isupper())
print("Somente minúsculas:", algo.islower())
print("Somente números:", algo.isnumeric())
print("Somente letras:", algo.isalpha())
print("É possível imprimir:", algo.isprintable())
print("Está capitalizada:", algo.istitle())
